from sqlalchemy.orm import Session
import uuid

from app.repositories import feature_repository
from app.repositories import estimate_repository


def generate_mvp_recommendation(db: Session, project_id: uuid.UUID):
    """
    Deterministically recommend an MVP scope from the project's extracted
    features.

    MVP scope is driven by feature priority (high / medium / low). The result
    is explainable rather than generated by the LLM, matching the guide's
    requirement that costs/scope logic stay in deterministic code.
    """
    features = feature_repository.list_features(db, project_id)

    if not features:
        return {
            "project_id": project_id,
            "recommendation_possible": False,
            "mvp_features": [],
            "phase_2_features": [],
            "later_features": [],
            "reasoning": "No features have been extracted yet. Run analysis first.",
            "estimated_hours_range": None,
        }

    high = [f for f in features if f.priority == "high"]
    medium = [f for f in features if f.priority == "medium" and f not in high]
    low = [f for f in features if f.priority == "low"]

    # If nothing is high priority, fall back to the smallest set of essential
    # features so the MVP is never empty.
    if not high and medium:
        high = [medium[0]]
        medium = medium[1:]

    def _feature_dict(f):
        return {
            "id": f.id,
            "canonical_name": f.canonical_name,
            "description": f.description,
            "priority": f.priority,
            "complexity": f.complexity,
        }

    reasoning = (
        f"The MVP should focus on the {len(high)} core "
        + ("feature" if len(high) == 1 else "features")
        + " that deliver the primary value of the product: "
        + ", ".join(f.canonical_name.lower().replace("_", " ") for f in high)
        + ". Non-essential capabilities are deferred to later phases to ship "
        + "value quickly and validate the idea with the smallest usable scope."
    )

    estimate = estimate_repository.get_estimate(db, project_id)
    hours_range = None
    if estimate and estimate.min_hours is not None:
        hours_range = {
            "min": round(estimate.min_hours, 1),
            "expected": round(estimate.expected_hours, 1),
            "max": round(estimate.max_hours, 1),
        }

    return {
        "project_id": project_id,
        "recommendation_possible": True,
        "mvp_features": [_feature_dict(f) for f in high],
        "phase_2_features": [_feature_dict(f) for f in medium],
        "later_features": [_feature_dict(f) for f in low],
        "reasoning": reasoning,
        "estimated_hours_range": hours_range,
    }
