"""add category to requirements

Revision ID: 341476ee91a7
Revises: 38b035c73b7a
Create Date: 2026-08-28 23:25:09.228467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341476ee91a7'
down_revision: Union[str, Sequence[str], None] = '38b035c73b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'category')
    # ### end Alembic commands ###
