"""add task scheduling fields

Revision ID: 856099b92bd0
Revises: 7af53276b69f
Create Date: 2026-09-03 18:19:21.945107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856099b92bd0'
down_revision: Union[str, Sequence[str], None] = '7af53276b69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('depends_on', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_date')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'depends_on')
    # ### end Alembic commands ###
