"""add risk category severity and score

Revision ID: df3e8ca39815
Revises: a1b2c3d4e5f6
Create Date: 2026-09-05 01:33:07.247217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3e8ca39815'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add nullable columns with server defaults so existing rows get values.
    op.add_column(
        'risks',
        sa.Column('category', sa.String(), nullable=True, server_default="technical"),
    )
    op.add_column(
        'risks',
        sa.Column('severity', sa.String(), nullable=True, server_default="medium"),
    )
    op.add_column(
        'risks',
        sa.Column('risk_score', sa.Float(), nullable=True, server_default="4.0"),
    )

    # 2. Backfill existing rows (safe no-op for rows already populated).
    op.execute("UPDATE risks SET category = 'technical' WHERE category IS NULL")
    op.execute("UPDATE risks SET severity = 'medium' WHERE severity IS NULL")
    op.execute("UPDATE risks SET risk_score = 4.0 WHERE risk_score IS NULL")

    # 3. Enforce NOT NULL once every row has a value.
    op.alter_column('risks', 'category', existing_type=sa.String(), nullable=False)
    op.alter_column('risks', 'severity', existing_type=sa.String(), nullable=False)
    op.alter_column('risks', 'risk_score', existing_type=sa.Float(), nullable=False)

    # 4. Remove server defaults (app-level defaults handle future inserts).
    op.alter_column(
        'risks', 'category', existing_type=sa.String(), server_default=None
    )
    op.alter_column(
        'risks', 'severity', existing_type=sa.String(), server_default=None
    )
    op.alter_column(
        'risks', 'risk_score', existing_type=sa.Float(), server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'risk_score')
    op.drop_column('risks', 'severity')
    op.drop_column('risks', 'category')
    # ### end Alembic commands ###
